---
build_from:
   amd64: "ghcr.io/home-assistant/amd64-base-debian:latest"
   aarch64: "ghcr.io/home-assistant/aarch64-base-debian:latest"
args:
   NEOHUB_IMAGE: "ghcr.io/brianhumlicek/neohub:sha-4604126"
